version: "4.38"

services:
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  task-service:
    build:
      context: ./services/task-service
    container_name: task-service
    environment:
      - NODE_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - redis
    restart: always

  notification-service:
    build:
      context: ./services/notification-service
    container_name: notification-service
    environment:
      - NODE_ENV=development
    ports:
      - "5003:5003"
    depends_on:
      - redis
    restart: always

  bullmq-ui:
    image: hive/bull-arena
    container_name: bullmq-ui
    ports:
      - "3001:4567"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
